name: Verify Flags & Update Leaderboard

on:
  pull_request_target:
    types: [opened, synchronize]

permissions:
  contents: write
  pull-requests: write

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          
      - name: Verify submitted flags
        env:
          CTF_SECRET: ${{ secrets.CTF_SECRET }}
        run: python3 verify_flags.py

      - name: Update Leaderboard
        run: python3 update_leaderboard.py

      - name: Commit leaderboard changes
        run: |
          git config user.name "gh0stCTF Bot"
          git config user.email "bot@gh0stctf.com"
          git checkout -b temp-branch
          git add leaderboard/
          git commit -m "Update leaderboard [bot]" || echo "No changes"
          git push origin HEAD:refs/heads/${{ github.event.pull_request.head.ref }}
